### ISSUE TITLE
wiki of devtools is no more, sends you to adv-r.hadley.co.nz

### ISSUE THREAD

**Issue by RMHogervorst** [ropensci/styleguide#13]
At the bottom of the page:

```
Further guidance

    The devtools package and its wiki are (...)
```

However the wiki in the devtools repo has been replaced with

`Page moved to http://adv-r.had.co.nz/ and/or https://github.com/hadley/adv-r/ .`

i suggest to rephrase:
`The devtools package and the book advanced r` with a link to the book. 

> `Tis but a scratch

**Comment by sckott** [comment]
thanks @RMHogervorst

**Comment by maelle** [comment]
The link doesn't exist any more in https://github.com/ropensci/dev_guide so it must have been solved.

Broken links can also be found by regularly running https://github.com/ropensci/dev_guide/blob/master/inst/book_grooming.R

Closing this before archiving the repo since development of guidelines moved to https://github.com/ropensci/dev_guide
