### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by richfitz** [ropensci/styleguide#3]
Something about 
- Semantic versioning
- Bumping the version number after going through CRAN
- Development version numbers (there seems to be some convention with .9000 that is totally opaque to me)

**Comment by cboettig** [comment]
Yup, great idea.

Re: `.9000`, I believe that appending a `.90` or `.99` etc to the end of the `x.y.z` semantic version is a practice adopted by @hadley (and maybe more RStudio's developers more broadly) just as quick & easy way to see if a user had a CRAN-released version or a Github version from their `sessionInfo` when trying to debug some issue.  I think @yihui has always just used the `.z` place to indicate the pre-CRAN release version of knitr though -- I too could use clarification on the details of these conventions for identifying the in-development versions.

**Comment by karthik** [comment]
There is more notes on this in Hadley's R packaging book. But I do like the idea that we advocate for CRAN and GitHub versions making it easier to troubleshoot issues.

**Comment by sckott** [comment]
Right, a few other thoughts
- `git tag` all versions that go to CRAN, and maybe others as needed - and puts related `NEWS` for each tag in `Releases`
- suggest using Milestones on Github to help track issues associated with versions

What @cboettig said regarding `.9000` - I think we started doing that recently following their lead. It is kind of nice to have when people are reporting bugs etc to immediately know where they got the pkg. 

Do we want to follow Yihui's lead and only push minor versions (e.g., `0.4.0`) to CRAN?  I think this is laudable, but in practice, since most of our pkgs work with web APIs, we may have to push a patch version if the web API breaks the package.

**Comment by karthik** [comment]
> Do we want to follow Yihui's lead and only push minor versions (e.g., 0.4.0) to CRAN? I think this is laudable, but in practice, since most of our pkgs work with web APIs, we may have to push a patch version if the web API breaks the package.

I think we can push every increment of `y` unless it is a critical patch that breaks functionality. Switching to say, dplyr, for faster data munging is something that can wait. But a change in API end point would be a more serious reason for an earlier update.

**Comment by karthik** [comment]
Also `session_info` from `devtools` reports CRAN versus GitHub versions and also the commit from which it was installed. So that is also a nice feature when looking for the `9k` version.

**Comment by sckott** [comment]
@richfitz @cboettig @karthik  i added stuff about versioning, change as needed

**Comment by sckott** [comment]
i think this is done, reopen if not
